config/routes.rb
Rails.application.routes.draw do
  resources :conversations
  resources :user_chats
  resources :chats
  resources :trainers
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#hello'
  root 'users#index'
  root 'trainers#index'
end

app/models/user_chat.rb
class UserChat < ApplicationRecord
end

app/controllers/user_chats_controller.rb
class UserChatsController < ApplicationController
  before_action :set_user_chat, only: [:show, :edit, :update, :destroy]

  # GET /user_chats
  # GET /user_chats.json
  def index
    @user_chats = UserChat.all
  end

  # GET /user_chats/1
  # GET /user_chats/1.json
  def show
  end

  # GET /user_chats/new
  def new
    @user_chat = UserChat.new
  end

  # GET /user_chats/1/edit
  def edit
  end

  # POST /user_chats
  # POST /user_chats.json
  def create
    @user_chat = UserChat.new(user_chat_params)

    respond_to do |format|
      if @user_chat.save
        format.html { redirect_to @user_chat, notice: 'User chat was successfully created.' }
        format.json { render :show, status: :created, location: @user_chat }
      else
        format.html { render :new }
        format.json { render json: @user_chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_chats/1
  # PATCH/PUT /user_chats/1.json
  def update
    respond_to do |format|
      if @user_chat.update(user_chat_params)
        format.html { redirect_to @user_chat, notice: 'User chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_chat }
      else
        format.html { render :edit }
        format.json { render json: @user_chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_chats/1
  # DELETE /user_chats/1.json
  def destroy
    @user_chat.destroy
    respond_to do |format|
      format.html { redirect_to user_chats_url, notice: 'User chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_chat
      @user_chat = UserChat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_chat_params
      params.require(:user_chat).permit(:user1_id, :user2_id, :chat_id)
    end
end

app/helpers/user_chats_helper.rb
module UserChatsHelper
end

app/views/user_chats/_form.html.erb
<%= form_with(model: user_chat, local: true) do |form| %>
  <% if user_chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_chat.errors.count, "error") %> prohibited this user_chat from being saved:</h2>

      <ul>
      <% user_chat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user1_id %>
    <%= form.number_field :user1_id, id: :user_chat_user1_id %>
  </div>

  <div class="field">
    <%= form.label :user2_id %>
    <%= form.number_field :user2_id, id: :user_chat_user2_id %>
  </div>

  <div class="field">
    <%= form.label :chat_id %>
    <%= form.number_field :chat_id, id: :user_chat_chat_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_chats/edit.html.erb
<h1>Editing User Chat</h1>

<%= render 'form', user_chat: @user_chat %>

<%= link_to 'Show', @user_chat %> |
<%= link_to 'Back', user_chats_path %>

app/views/user_chats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Chats</h1>

<table>
  <thead>
    <tr>
      <th>User1</th>
      <th>User2</th>
      <th>Chat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chat.each do |chat| %>
      <tr>
        <td><%= chat.user1_id %></td>
        <td><%= chat.user2_id %></td>
        <td><%= chat.chat_id %></td>
        <td><%= link_to 'Show', chat %></td>
        <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
        <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Chat', new_user_chat_path %>

app/views/user_chats/new.html.erb
<h1>New User Chat</h1>

<%= render 'form', user_chat: @user_chat %>

<%= link_to 'Back', user_chats_path %>

app/views/user_chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User1:</strong>
  <%= @user_chat.user1_id %>
</p>

<p>
  <strong>User2:</strong>
  <%= @user_chat.user2_id %>
</p>

<p>
  <strong>Chat:</strong>
  <%= @user_chat.chat_id %>
</p>

<%= link_to 'Edit', edit_user_chat_path(@user_chat) %> |
<%= link_to 'Back', user_chats_path %>